name: Passive Income Apps

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIST_URL: ${{ secrets.ACCOUNTFILESOURCE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-docker@v2

      - name: Download accounts.txt enviro
        run: |
          curl -L $GIST_URL -o .env

      - name: Run Docker image
        run: |
          docker run -d jojogamezHub/money4funn:main

      - name: Sleep for 8 hours
        run: sleep 28800  # Sleep for 8 hours (adjust as needed)

      - name: Stop Docker stack
        run: sudo docker-compose down
